# VHS https://github.com/charmbracelet/vhs
Output demo.gif
Hide
Set Shell pwsh
Type "Import-Module ../.publish/StainedGlass.psd1"
Enter
Type "Clear-Host"
Enter
Show
Type "Get-SystemDetails"
Enter
Sleep 9s
Type "Get-ADUserStatus $env:USERNAME"
Enter
Sleep 9s
Type "Test-WindowsTerminal"
Enter
Sleep 3s
Type "Get-DotNetFrameworkVersions"
Enter
Sleep 4s
Type "Get-DotNetVersions"
Enter
Sleep 4s
Type "Measure-Caches"
Enter
Sleep 5s
Type "Get-SimpleSchTasks"
Enter
Sleep 9s
