# VHS https://github.com/charmbracelet/vhs
Output demo.gif
Hide
Set Shell pwsh
Type "Import-Module ../.publish/StainedGlass.psd1"
Enter
Type "Clear-Host"
Enter
Show
Type "Get-SystemDetails"
Enter
Sleep 6s
Type "Test-WindowsTerminal"
Enter
Sleep 3s
Type "Get-DotNetFrameworkVersions"
Enter
Sleep 4s
Type "Get-DotNetVersions"
Enter
Sleep 4s
Type "Get-SimpleSchTasks |Select-Object -First 1"
Enter
Sleep 6s
Type "Get-Item ~/Downloads/git"
Tab
Type " |Get-ZoneInfo"
Enter
Sleep 8s
